title: Investigation in Memory
description: A deep analysis of a Volatile memory capture file and an investigation of one or more cyber attacks
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
